name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag my-image-name:$(date +%s)
